### ISSUE TITLE
Help with understanding some of the functionality

### ISSUE THREAD

**Issue by si2030** [joeaudette/cloudscribe.Web.SimpleAuth#1]
Hi Joe,

I am using both Navigation and Pagination.  I have been looking at simpleAuth with a view to using this as well. Wondering if you might give me some further info on some of the functionality as I in a particularly steep learning curve at the moment.

I was looking at the SimpleAuthSettings.json file and would like to know how to bring up the different tennants - ones called "Sample site" and the other is called "darkly industries". Each has a different theme under the themes folder.

How do I use the Hostnames that appear in the simpleauthsettings.jason

I've noticed that I use annotations to manage role authorization as per the controller. Can I have multiple roles accessing one IActionResult - that is, having multiple roles in the one annotation or do I have to have multiple annotations.

Do all my views and viewmodels go in the Theme folder as per the "Index_tenant-1.cshtml" view if I want that theme to be used...

My intention is to use this with a single tennant rather than multi tenancy..

Do I comment out the multitennant service and un comment the single tennant service option

services.Configure< SimpleAuthSettings >(Configuration.GetSection("SimpleAuthSettings"));
            //services.AddScoped< IUserLookupProvider, DefaultUserLookupProvider >(); // single tenant

I suspect doing this will mean I only need one theme in the themes folder.

Finally, how do I configure Recaptcha...

Kind Regards
Simon

**Comment by joeaudette** [comment]
Hi Simon,

I have added a samples folder in the repository and created 2 samples, one single tenant, and one as multi-tenant.
These samples should be easier to understand because they only have the Nuget for SimpleAuth, not the source code, so it is how your own project should look.

I've added a readme.md file in the project root of the multi tenant example with notes about how to easily test it with 2 "host" tenants running at once

I've added comments in the simpleauthsettings.json file examples with a link to get your recaptcha keys, as soon as the keys are populated the recaptcha should appear on the login page

In the mutli tenant readme I think I have also answered the questions about themes
I only implemented the themes in the multi tenant demo to make it more clear which tenant one is viewing and to show how to theme different tenants, you would not need that in a single tenant app though it still might be nice to be able to easily change the theme of a single tenant app while keeping the previous theme intact

for your question about authorization I recommend see the docs here to learn the various ways to configure authorization policy
https://docs.asp.net/en/latest/security/authorization/index.html

**Comment by si2030** [comment]
Much appreciated Joe.. Will check it out Monday… Regards Simon
