### ISSUE TITLE
Question about getting started documentation

### ISSUE THREAD

**Issue by glaxaco** [joeaudette/cloudscribe.Web.SimpleAuth#6]
I'm working through the steps for getting started in the README file. In Step 7, you say "copy the Views/Login folder from the example.WebApp project into your own project." However, the example.WebApp project does not contain a Views/Login folder - do you mean the cloudscribe.Web.SimpleAuth project? Thanks.

**Comment by joeaudette** [comment]
yes, sorry the readme was badly out of date, I have updated it. Note also that unless you want to customize the views you can also use them as embedded resources and they are already embedded in the nuget. I've added info about that on the readme as well.

Note also since [cloudscribe Core](https://www.cloudscribe.com/docs/cloudscribe-core) supports NoDb file system storage and provides nice management features, I am generally using it even for small projects myself instead of using SimpleAuth but nothing wrong with using SimpleAuth if it meets your needs.
